# Generated by Django 4.2.4 on 2023-09-04 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('brand', models.CharField(default='', max_length=200)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Arts', 'Arts'), ('Food', 'Food'), ('Laptops', 'Laptops'), (' Home', 'Home'), ('Kitchen', 'Kitchen')], max_length=30)),
                ('ratings', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('stock', models.IntegerField(default=0)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
