# Generated by Django 4.2.5 on 2023-09-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ratings',
            new_name='rating',
        ),
    ]
