# Generated by Django 4.2.5 on 2023-09-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_order_status_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='images',
            field=models.CharField(default='', max_length=500),
        ),
    ]
